def getListJobs():
    jobs = [
            'developer',
            'data scientist',
            'data analyst',
            'database developer',
            'database administrator',
            'statistician',
            'machine learning engineer',
            'business intelligence analyst',
            'business analyst',
            'chief data officer',
            'chief analytics officer',
            'big data engineer',
            'data analytics manager',
            'data security administrator'
            'data protection officer',
            'data architect',
            'data engineer',
            'data consultant',
            'data visualisation consultant',
            'dataops engineer',
            'data steward',
            'data miner',
            'cloud architect',
            'cloud consultant',
            'cloud product and project manager',
            'cloud Services Developer',
            'cloud software and network engineer',
            'cloud system administrator',
            'cloud system engineer',
            'computer and information research scientist',
            'computer and information systems manager',
            'computer network architect',
            'computer systems analyst',
            'computer systems manager',
            'it analyst',
            'it coordinator',
            'network administrator',
            'network architect',
            'network and computer systems administrator',
            'network engineer',
            'network systems administrator',
            'senior network architect',
            'senior network engineer',
            'senior network system administrator',
            'telecommunications specialist',
            'customer support administrator',
            'customer support specialist',
            'desktop support manager',
            'desktop support specialist',
            'help desk specialist',
            'help desk technician',
            'it support manager',
            'it support specialist',
            'it systems administrator',
            'senior support specialist',
            'senior system administrator',
            'support specialist',
            'systems administrator',
            'technical specialist',
            'technical support engineer',
            'technical support specialist',
            'data center support specialist',
            'data quality manager',
            'database administrator',
            'senior database administrator',
            'application support analyst',
            'senior system analyst',
            'systems analyst',
            'systems designer',
            'chief information officer (cio)',
            'chief technology officer (cto)',
            'director of technology',
            'it director',
            'it manager',
            'management information systems director',
            'technical operations officer',
            'information security analyst',
            'security specialist',
            'senior security specialist',
            'application developer',
            'applications engineer',
            'associate developer',
            'computer programmer',
            'developer',
            'java developer',
            'junior software engineer',
            '.net developer',
            'programmer',
            'programmer analyst',
            'senior applications engineer',
            'senior programmer',
            'senior programmer analyst',
            'senior software engineer',
            'senior system architect',
            'senior system designer',
            'senior systems software engineer',
            'software architect',
            'software developer',
            'software engineer',
            'software quality assurance analyst',
            'system architect',
            'systems software engineer',
            'front end developer',
            'senior web administrator',
            'senior web developer',
            'web administrator',
            'web developer'
        ]
    return jobs